Header and headline sections of portfolio
Solo7991/Microverse-Portfolio pull request #1
Opened 2022-04-20 13:16 UTC by Solo7991

The two sections of the portfolio
Linters such as lighthouse, webhint, and stylelint

2022-04-21 16:22 UTC, Danieldotcomcoder reviewed
Hi @Solo7991, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a descriptive Readme file 😃
Please use this  [Template]( https://github.com/microverseinc/readme-template/blob/master/README.md) to add a readme file to your project ✔👍


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏👍✔

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-04-21 17:04 UTC, JuliCarracedo reviewed
Hi @Solo7991 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is not using any of the provided [Figma designs](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).
Even though your design is really interesting, you ar ealso being tested on your ability to translate designs into technical solutions so you must use one of the provided designs. I'd recommend Template 5 since it's the closest to your aspirations.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-04-22 15:54 UTC, uche-inyama requested changes
### Hi @Solo7991 :slightly_smiling_face: 

Good job so far, and I must commend your efforts.

There are some issues that you still need to work on, you are almost there!




## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 15:54 UTC, uche-inyama commented on index.html
> +      <!-- headline end -->
Kindly wrap this section with a **section** tag.

2022-04-22 15:54 UTC, uche-inyama commented on index.html
> +        </div>
List the icons with a ul and li tags. Also, wrap the image with an **a** tag. As each icon should navigate to webpage.

## :slightly_smiling_face:

2022-04-22 17:13 UTC, ShahierNashaat approved these changes
Hi @Solo7991 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Approved :ok_hand: :ok_hand: :ok_hand:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 17:19 UTC, merged